# Generated by Django 4.2.14 on 2024-08-27 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='car_model',
            field=models.CharField(default=206, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='send_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(default='206', on_delete=django.db.models.deletion.PROTECT, related_name='alert', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
    ]
