# Generated by Django 4.2.14 on 2024-09-10 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_alter_car_body'),
        ('notification', '0003_alter_notification_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='car_model',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='send_at',
        ),
        migrations.AddField(
            model_name='notification',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='car.car'),
            preserve_default=False,
        ),
    ]
