# Generated by Django 4.2.14 on 2024-09-21 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_remove_notification_car_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
    ]
