# Generated by Django 4.2.14 on 2024-08-19 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body',
            field=models.SmallIntegerField(choices=[(1, 'None'), (2, '1piece'), (3, '2pieces'), (4, 'whole_color')], null=True),
        ),
    ]
