# Generated by Django 4.2.14 on 2024-09-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_alter_car_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, max_length=256),
        ),
    ]
